name: Build ImmortalWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean old feeds
      run: rm -rf feeds/*

    - name: Update feeds
      run: |
        ./scripts/feeds clean
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Build firmware
      run: |
        make defconfig
        make -j$(nproc)
